// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


float airPressure;
float humInsideDevice;
float tempInsideDevice;
int humOutsideDevice;
int illuminance;
int tempOutsideDevice;
bool pIRMotion;

void initProperties(){

  ArduinoCloud.addProperty(airPressure, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(humInsideDevice, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(tempInsideDevice, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(humOutsideDevice, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(illuminance, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(tempOutsideDevice, READ, 30 * SECONDS, NULL);
  ArduinoCloud.addProperty(pIRMotion, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);